# Docker Compose Override for Insights On-Premise Dependencies
# This file overrides the original docker-compose.yml to use quay.io/insights-onprem images
# 
# Usage:
# 1. Copy this file to your ros-ocp-backend/scripts/ directory
# 2. Run: docker-compose up -d
# 
# Docker Compose will automatically merge this with docker-compose.yml

version: "3.8"
services:
  # Override Redis to use insights-onprem image
  redis:
    image: quay.io/insights-onprem/redis-ephemeral:6
    environment:
      - REDIS_MAXMEMORY=512mb
      - REDIS_MAXMEMORY_POLICY=allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # Override Insights Ingress to use insights-onprem image
  ingress:
    image: quay.io/insights-onprem/insights-ingress:latest
    # All other configuration remains the same
    
  # Override Sources API Go to use insights-onprem image
  sources-api-go:
    image: quay.io/insights-onprem/sources-api-go:latest
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db-sources
      - DATABASE_PORT=5432
      - DATABASE_NAME=sources_api_development
      - LOG_LEVEL=DEBUG
      - REDIS_CACHE_HOST=redis
      - REDIS_CACHE_PORT=6379
      - BYPASS_RBAC=true
      - QUEUE_HOST=kafka
      - QUEUE_PORT=29092    
      - ENCRYPTION_KEY=YWFhYWFhYWFhYWFhYWFhYQ
      - SOURCES_ENV=prod
    # All other configuration remains the same
    
  # For Zookeeper mode, we need to use the 7.5.3 Kafka image
  kafka:
    image: confluentinc/cp-kafka:7.5.3

  kafka-create-topics:
    image: confluentinc/cp-kafka:7.5.3

  # Override Sources DB Setup to use insights-onprem image
  # Disabled since database is already initialized
  sources-db-setup:
    image: quay.io/insights-onprem/sources-api-go:latest
    restart: "no"
    command: "echo 'Database already initialized, skipping setup'"
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db-sources
      - DATABASE_PORT=5432
      - DATABASE_NAME=sources_api_development
      - LOG_LEVEL=DEBUG
      - REDIS_CACHE_HOST=redis
      - REDIS_CACHE_PORT=6379
      - BYPASS_RBAC=true
      - QUEUE_HOST=kafka
      - QUEUE_PORT=29092        
      - ENCRYPTION_KEY=YWFhYWFhYWFhYWFhYWFhYQ
      - SOURCES_ENV=prod
    # All other configuration remains the same

